language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x

install:
  - go get golang.org/x/tools/cmd/cover
  - go list -f '{{range .Imports}}{{.}} {{end}}' ./... | xargs go get -d -v
  - go list -f '{{range .TestImports}}{{.}} {{end}}' ./... | xargs go get -d -v

gobuild_args: -v -race
